# Copyright 2025 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: charm tests

on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming:
    name: Inclusive naming
    uses: canonical/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "false"

  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  linting:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox --with tox-uv
          tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Static analysis
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox --with tox-uv
          tox -e static

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit tests
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox --with tox-uv
          tox -e unit

  pack-charm:
    name: Pack the charm
    needs:
      - linting
      - static-analysis
      - unit-tests
    uses: ./.github/workflows/pack.yaml
    with:
      name: microcluster-token-distributor

  test:
    runs-on: ubuntu-latest
    needs:
      - pack-charm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: microcluster-token-distributor
      - run: |
          # NOTE this here to demonstrate use of workflow,
          #      replace with actual tests.
          echo ${{ needs.pack.outputs.charms }}
          for charm in ${{ needs.pack.outputs.charms }}; do
            mkdir charm
            pushd charm
            unzip ../$charm
            popd
            rm -rf charm
          done
