name: Pull Request

on:
  pull_request:

jobs:
  pack:
    uses: ./.github/workflows/pack.yaml
    with:
      name: microcluster-token-distributor
  test:
    runs-on: ubuntu-latest
    needs:
      - pack
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: microcluster-token-distributor
      - run: |
          # NOTE this here to demonstrate use of workflow,
          #      replace with actual tests.
          echo ${{ needs.pack.outputs.charms }}
          for charm in ${{ needs.pack.outputs.charms }}; do
            mkdir charm
            pushd charm
            unzip ../$charm
            popd
            rm -rf charm
          done
